### ISSUE TITLE
The demo doesn't show ImGUI (on macOS)

### ISSUE THREAD

**Issue by toyboot4e** [aclysma/imgui-inspect#16]
`cargo run` on macOS showed:

<img width="900" alt="imgui-inspect-demo" src="https://user-images.githubusercontent.com/47905926/115939948-d945fb00-a4da-11eb-9947-ff1d9e3e96fc.png">

I expected there is an ImGUI window as in README. Does it seem like a bug on macOS? Thank you.

**Comment by aclysma** [comment]
Worked fine for me:

![image](https://user-images.githubusercontent.com/316070/115980475-df22f700-a541-11eb-8531-b69cbdcb6090.png)

**Comment by toyboot4e** [comment]
Sorry, even the image in README was using macOS window. Well I can give up.

By the way, `rafx` is so cool :) Thank you for spending time, have a nice day!

**Comment by aclysma** [comment]
If you want to try to debug further:
 * Try a fresh clone and see if it works (just to eliminate the possibility of local changes breaking it)
 * I would printf/breakpoint to verify that the imgui vertex data seems reasonable (i.e. coordinates fit within the window)
 * You can attach xcode and do a metal frame capture. But it's something you would need to figure out how to do on your own. (Hint: make an empty project, change the project settings to launch the executable in target and use the correct local directory. there might be a box to check to force metal debugging, then capture as normal.) This is probably only useful if you're already familiar with graphics programming.
