### ISSUE TITLE
not building (on linux)

### ISSUE THREAD

**Issue by zertyz** [aclysma/imgui-inspect#4]
"cargo (v. 1.42.0) run" fails with:

(...)
   Compiling imgui-inspect-demo v0.1.0 (/home/luiz/tmp/git/imgui-inspect/imgui-inspect-demo)
error[E0308]: mismatched types
   --> imgui-inspect-demo/src/imgui_support.rs:115:57
    |
115 |                 platform.handle_event(context.io_mut(), &window, &event);
    |                                                         ^^^^^^^ expected struct `winit::window::Window`, found `&winit::window::Window`
    |
    = note: expected reference `&winit::window::Window`
               found reference `&&winit::window::Window`

error[E0308]: mismatched types
   --> imgui-inspect-demo/src/imgui_support.rs:115:66
    |
115 |                 platform.handle_event(context.io_mut(), &window, &event);
    |                                                                  ^^^^^^ expected enum `winit::event::Event`, found reference
    |
    = note: expected reference `&winit::event::Event<'_, _>`
               found reference `&&winit::event::Event<'_, T>`

error[E0308]: mismatched types
   --> imgui-inspect-demo/src/imgui_support.rs:189:52
    |
189 |             .prepare_frame(inner.context.io_mut(), window)
    |                                                    ^^^^^^ expected struct `winit::window::Window`, found a different struct `winit::window::Window`
    |
    = note: expected reference `&winit::window::Window` (struct `winit::window::Window`)
               found reference `&winit::window::Window` (struct `winit::window::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> imgui-inspect-demo/src/imgui_support.rs:228:48
    |
228 |             inner.platform.prepare_render(&ui, window);
    |                                                ^^^^^^ expected struct `winit::window::Window`, found a different struct `winit::window::Window`
    |
    = note: expected reference `&winit::window::Window` (struct `winit::window::Window`)
               found reference `&winit::window::Window` (struct `winit::window::Window`)
    = note: perhaps two different versions of crate `winit` are being used?

error[E0308]: mismatched types
   --> imgui-inspect-demo/src/imgui_support.rs:319:9
    |
319 |         &window,
    |         ^^^^^^^ expected struct `winit::window::Window`, found `&winit::window::Window`
    |
    = note: expected reference `&winit::window::Window`
               found reference `&&winit::window::Window`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `imgui-inspect-demo`.

To learn more, run the command again with --verbose.

**Comment by aclysma** [comment]
Latest should fix it
